name = "hono-drizzle-todo"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "todo-db"
database_id = "d6a53054-af8c-4703-9c10-994a3eb51410"
migrations_dir = "drizzle"

[build]
command = "npm run build"

[[d1_databases.migrations]]
dir = "drizzle"

[build.upload]
format = "modules"
main = "./src/index.ts" 